apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 820242910172.dkr.ecr.eu-west-1.amazonaws.com/final-project-ecr-repo:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "mydatabase"
            - name: DATABASE_HOST
              value: "final-project-db-instance.cp4uqqyiq3l6.eu-west-1.rds.amazonaws.com"
            - name: DATABASE_PORT
              value: "5432"
